CMS/DMS.PL/Controllers/AppointmentController.cs
using DMS.BLL.Interfaces;
using DMS.BLL.Services;
using DMS.BLL.ViewModels;
using DMS.DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DMS.PL.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly IAppointmentService appointmentService;
        private readonly IDoctorService doctorService;
        private readonly IPatientService patientService;

        public AppointmentController(IAppointmentService appointmentService,IDoctorService doctorService , IPatientService patientService) 
        {
            this.appointmentService = appointmentService;
            this.doctorService = doctorService;
            this.patientService = patientService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var appointments = await appointmentService.GetAll();
                return View(appointments);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while retrieving appointments.");
                return View(new List<AppointmentVM>());
            }
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await PopulateViewData();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(AppointmentVM model)
        {
            try
            {

                if (model.PatientId == 0)
                {

                    var existingPatientId = await patientService.GetPatientIdByNameAsync(model.PatientName);

                    if (existingPatientId.HasValue)
                    {
                        model.PatientId = existingPatientId.Value;
                    }
                    else
                    {
                        var newPatient = new PatientVM
                        {
                            Name = model.PatientName,
                            BirthDate = model.PatientBirthDate,
                            Address = model.PatientAddress,
                            PhoneNumber = model.PatientPhoneNumber,
                            SSN = model.PatientSSN
                        };
                        await patientService.Create(newPatient);

                        // Retrieve the newly created patient ID

                        var createdPatientId = await patientService.GetPatientIdByNameAsync(model.PatientName);
                        if (createdPatientId.HasValue)
                        {
                            model.PatientId = createdPatientId.Value;
                        }
                        else
                        {
                            ModelState.AddModelError("", "Failed to retrieve the newly created patient ID.");
                            return View(model);
                        }
                    }

                    await appointmentService.Create(model);

                    return RedirectToAction("Index");
                }

                await PopulateViewData();
                return View(model);

            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while creating the user.");
                await PopulateViewData();
                return View(model);

            }
            
        }

      
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var appointment = await appointmentService.GetById(id);
                if (appointment == null)
                {
                    return NotFound();

                }
                await PopulateViewData();
                return View(appointment);
            }catch(Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while retrieving the appointment.");
                return RedirectToAction(nameof(Index));
            }
           
        }
        [HttpPost]
        public async Task<IActionResult> Edit(AppointmentVM appointmentVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await PopulateViewData();

                    await appointmentService.UpdateAsync(appointmentVM);
                    return RedirectToAction(nameof(Index));
                }

                await PopulateViewData();
                return View(appointmentVM);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while updating the appointment.");
                return View(appointmentVM);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var appointment = await appointmentService.GetById(id);
            if (appointment == null)
            {
                return NotFound();
            }
            return View(appointment);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {

                await appointmentService.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while deleting the appointment.");
                return RedirectToAction(nameof(Index));
            }
        }


        private async Task PopulateViewData()
        {
            var doctors = await doctorService.GetAll();
            ViewBag.Doctors = new SelectList(doctors, "Id", "Name");
            var patients = await patientService.GetAll();
            ViewBag.Patients = new SelectList(patients, "Id", "Name");
        }

        [HttpGet]
        public async Task<IActionResult> GetAvailableSlots(int doctorId, DateTime date)
        {
            try
            {
                var slots = await appointmentService.GetAvailableSlots(doctorId, date);
                return Json(slots);
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }
    }
}

CMS/DMS.PL/Controllers/DoctorController.cs
using DMS.BLL.Interfaces;
using DMS.BLL.Services;
using DMS.BLL.ViewModels;
using DMS.DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Numerics;

namespace DMS.PL.Controllers
{
    public class DoctorController : Controller
    {
        private readonly IDoctorService doctorService;
        private readonly IAppointmentService appointmentService;
        private readonly IShiftService shiftService;

        public DoctorController(IDoctorService doctorService,IAppointmentService appointmentService,IShiftService shiftService)
        {
            this.doctorService = doctorService;
            this.appointmentService = appointmentService;
            this.shiftService = shiftService;
        }

		[HttpGet]
		public async Task<IActionResult> GetDoctors()
		{
            try
            {
                var doctors = await doctorService.GetAll();
                var shifts = await shiftService.GetAll();
                return View(doctors);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while retrieving the list of doctors.");
                return View("Error");
            }
        }

		[HttpGet]
        public async Task<IActionResult> Profile(int id)
        {
            try
            {
                var doctor = await doctorService.GetById(id);
                if (doctor == null)
                {
                    return NotFound();
                }

                return View(doctor);
            }catch(Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while showing data");

            }
            return NotFound();

        }
        [HttpGet]
        public  async Task<IActionResult> Create()
        {
            var shifts = await shiftService.GetAll();
            ViewBag.Shifts = new SelectList(shifts, "Id" ,"DisplayShift" );
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(DoctorVM model)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    await doctorService.Create(model);
                    return RedirectToAction(nameof(GetDoctors));
                }
                var shifts = await shiftService.GetAll();
                ViewBag.Shifts = new SelectList(shifts, "Id" ,"DisplayShift");

                return View(model);
            }catch(Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while creating the user.");

            }
            return View(model);

        }



        public async Task<IActionResult> TodaysAppointments(int id)
        {
            try
            {
                ViewBag.DoctorId = id;
                TempData["DoctorId"] = id;
                var appointments = await appointmentService.GetTodaysAppointmentsByDoctorId(id);
                return View(appointments);
            }catch(Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while retrieving data");

            }
            return NoContent();

        }
        [HttpGet]
        public IActionResult AppointmentsByDateRange()
        {
            var model = new AppointmentsByDateRangeVM();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AppointmentsByDateRange(AppointmentsByDateRangeVM model)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    if (TempData["DoctorId"] !=null)
                    {
                        model.DoctorId = (int)TempData["DoctorId"];
                    }
                        model.Appointments = await appointmentService.GetAppointmentsByDateRange(model.DoctorId, model.DateFrom, model.DateTo);
                        return View(model);
                    
                }
               
            }catch(Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while retrieving data");
                return View("Error");
            }
            return View(model);

        }

        [HttpGet]
        public async Task<IActionResult> GetAppointments(int id)
        {
            var appointments = await appointmentService.GetTodaysAppointmentsByDoctorId(id);
            ViewBag.DoctorId = id;
            return View(appointments);
        }

    }
}

CMS/DMS.PL/Views/Doctor/AppointmentsByDateRange.cshtml
@model AppointmentsByDateRangeVM

@{
    ViewData["Title"] = "Appointments By Date Range";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View Appointments By Date Range</h2>

<form asp-action="AppointmentsByDateRange" method="post">
    <div class="form-group">
        <label asp-for="DateFrom" class="control-label">From</label>
        <input asp-for="DateFrom" class="form-control" type="date" />
        <span asp-validation-for="DateFrom" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="DateTo" class="control-label">To</label>
        <input asp-for="DateTo" class="form-control" type="date" />
        <span asp-validation-for="DateTo" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Filter" class="btn btn-outline-primary" />
    </div>
</form>

@if (Model.Appointments != null && Model.Appointments.Any())
{
    <h3>Appointments</h3>
    <table class="table">
        <thead>
            <tr>
                <th>Patient Name</th>
                <th>Appointment Date</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var appointment in Model.Appointments)
            {
                <tr>
                    <td>@appointment.PatientName</td>
                    <td>@appointment.AppointmentDate.ToShortDateString()</td>
                    <td>@appointment.StartTime.ToString("HH:mm")</td>
                    <td>@appointment.EndTime.ToString("HH:mm")</td>
                    <td>@appointment.Status</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No appointments found for the selected date range.</p>
}

<div>
    <a asp-controller="Home" asp-action="Index">Back to List</a>
</div>

CMS/DMS.PL/Views/Doctor/Create.cshtml
@model DoctorVM
@inject IShiftService ShiftService;


@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Doctor </h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">           
            <div class="form-group">
                <label asp-for="Name" class="control-label">Doctor Name</label>
                <input asp-for="Name" class="form-control"  placeholder="Enter Doctor Name"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" placeholder="Enter Email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ShiftId" class="control-label"></label>
                <select asp-for="ShiftId" asp-items="ViewBag.Shifts" class="form-control">
                    <option value="">Select Shift </option>
                </select>
                <span asp-validation-for="ShiftId" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
  
}

CMS/DMS.PL/Views/Doctor/GetAppointments.cshtml
@model IEnumerable<AppointmentVM>

@{
    ViewData["Title"] = "Appointments";
}

<h1 class="text-center">Appointments for Doctor</h1>

<table class="table">
    <thead>
        <tr>
            <th>Patient Name</th>
            <th>Appointment Date</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var appointment in Model)
        {
            <tr>
                <td>@appointment.PatientName</td>
                <td>@appointment.AppointmentDate.ToString("MM/dd/yyyy")</td>
                <td>@appointment.StartTime.ToString("hh:mm tt")</td>
                <td>@appointment.EndTime.ToString("hh:mm tt")</td>
                <td>@appointment.Status</td>
            </tr>
            <a asp-action="AppointmentsByDateRange" asp-route-id="Model.Id" class="btn btn-outline-secondary btn-sm">Profile</a>

        }
    </tbody>
</table>

CMS/DMS.PL/Views/Doctor/GetDoctors.cshtml
@model IEnumerable<DoctorVM>
@inject IShiftService ShiftService;
 
@{
    ViewData["Title"] = "Get Doctors";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var allShifts = ShiftService.GetAll().Result; 

}

<h1 class="text-md-center">All Doctors in Clinic</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-primary ">Create New</a>
</p>
<p>
    <a asp-controller="Appointment"  asp-action="Create" class="btn btn-outline-warning ">Create New Appointment</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Doctor Name</th>
            <th>Email</th>
            <th>Start Shift</th>
            <th>End Shift</th>
            <th>Profile</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Email</td>
                <td>@item.Shift?.StartTime.ToString("hh:mm tt")</td>
                <td>@item.Shift?.EndTime.ToString("hh:mm tt")</td>
             
                <td>
                    <a asp-action="Profile" asp-route-id="@item.Id" class="btn btn-outline-secondary btn-sm">Profile</a>
                </td>
            </tr>
        }
    </tbody>
</table>

CMS/DMS.PL/Views/Doctor/Profile.cshtml
@model DoctorVM
@inject IShiftService ShiftService;


@{
    ViewData["Title"] = "Doctor Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="card-header d-flex align-items-center justify-content-between" style="background-color: #4CAF50; color: white;">
                    <h4 class="card-title mb-0">
                        <i class="fas fa-user-md"></i> Doctor Profile
                    </h4>
                    
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <strong>Name:</strong>
                        </div>
                        <div class="col-sm-9">
                            @Model?.Name 
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-sm-3">
                            <strong>Email:</strong>
                        </div>
                        <div class="col-sm-9">
                            @Model?.Email 
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-sm-3">
                            <strong>Shift Start From :</strong>
                        </div>
                        <div class="col-sm-9">
                            @Model?.Shift?.StartTime.ToString("HH:mm ")
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-sm-3">
                            <strong>Shift End At :</strong>
                        </div>
                        <div class="col-sm-9">
                            @Model?.Shift?.EndTime.ToString("HH:mm ")
                        </div>
                    </div>
                </div>
                <div class="card-footer text-right">
                    <a asp-action="TodaysAppointments" asp-route-id="@Model?.Id" class="btn btn-outline-secondary"> View Appointments </a>


                </div>
            </div>
        </div>
    </div>
</div>

CMS/DMS.PL/Views/Doctor/TodaysAppointments.cshtml
@model IEnumerable<AppointmentVM>
@inject IShiftService ShiftService;


@{
    ViewData["Title"] = "TodaysAppointments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="custom-heading">Today's Appointments</h1>

<table class="table table-striped table-hover table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>Patient</th>
            <th>Appointment Date</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Status</th>
           
   
        </tr>
    </thead>
    <tbody>
        @foreach (var appointment in Model)
        {
            <tr>
                <td>@appointment.PatientName</td>
                <td>@appointment.AppointmentDate.ToString("yyyy-MM-dd")</td>
                <td>@appointment.StartTime.ToString("HH:mm ")</td>
                <td>@appointment.EndTime.ToString("HH:mm ")</td>
                <td>@appointment.Status</td>
            </tr>
        }
    </tbody>
    <a asp-controller="Doctor" asp-action="AppointmentsByDateRange" asp-route-id="@ViewBag.DoctorId" class="btn btn-outline-warning ">
        Filter By Time
    </a>
</table>