CMS/DMS.PL/Controllers/AppointmentController.cs
using DMS.BLL.Interfaces;
using DMS.BLL.Services;
using DMS.BLL.ViewModels;
using DMS.DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DMS.PL.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly IAppointmentService appointmentService;
        private readonly IDoctorService doctorService;
        private readonly IPatientService patientService;

        public AppointmentController(IAppointmentService appointmentService,IDoctorService doctorService , IPatientService patientService) 
        {
            this.appointmentService = appointmentService;
            this.doctorService = doctorService;
            this.patientService = patientService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var appointments = await appointmentService.GetAll();
                return View(appointments);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while retrieving appointments.");
                return View(new List<AppointmentVM>());
            }
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await PopulateViewData();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(AppointmentVM model)
        {
            try
            {

                if (model.PatientId == 0)
                {

                    var existingPatientId = await patientService.GetPatientIdByNameAsync(model.PatientName);

                    if (existingPatientId.HasValue)
                    {
                        model.PatientId = existingPatientId.Value;
                    }
                    else
                    {
                        var newPatient = new PatientVM
                        {
                            Name = model.PatientName,
                            BirthDate = model.PatientBirthDate,
                            Address = model.PatientAddress,
                            PhoneNumber = model.PatientPhoneNumber,
                            SSN = model.PatientSSN
                        };
                        await patientService.Create(newPatient);

                        // Retrieve the newly created patient ID

                        var createdPatientId = await patientService.GetPatientIdByNameAsync(model.PatientName);
                        if (createdPatientId.HasValue)
                        {
                            model.PatientId = createdPatientId.Value;
                        }
                        else
                        {
                            ModelState.AddModelError("", "Failed to retrieve the newly created patient ID.");
                            return View(model);
                        }
                    }

                    await appointmentService.Create(model);

                    return RedirectToAction("Index");
                }

                await PopulateViewData();
                return View(model);

            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while creating the user.");
                await PopulateViewData();
                return View(model);

            }
            
        }

      
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var appointment = await appointmentService.GetById(id);
                if (appointment == null)
                {
                    return NotFound();

                }
                await PopulateViewData();
                return View(appointment);
            }catch(Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while retrieving the appointment.");
                return RedirectToAction(nameof(Index));
            }
           
        }
        [HttpPost]
        public async Task<IActionResult> Edit(AppointmentVM appointmentVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await PopulateViewData();

                    await appointmentService.UpdateAsync(appointmentVM);
                    return RedirectToAction(nameof(Index));
                }

                await PopulateViewData();
                return View(appointmentVM);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while updating the appointment.");
                return View(appointmentVM);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var appointment = await appointmentService.GetById(id);
            if (appointment == null)
            {
                return NotFound();
            }
            return View(appointment);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {

                await appointmentService.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while deleting the appointment.");
                return RedirectToAction(nameof(Index));
            }
        }


        private async Task PopulateViewData()
        {
            var doctors = await doctorService.GetAll();
            ViewBag.Doctors = new SelectList(doctors, "Id", "Name");
            var patients = await patientService.GetAll();
            ViewBag.Patients = new SelectList(patients, "Id", "Name");
        }

        [HttpGet]
        public async Task<IActionResult> GetAvailableSlots(int doctorId, DateTime date)
        {
            try
            {
                var slots = await appointmentService.GetAvailableSlots(doctorId, date);
                return Json(slots);
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }
    }
}

CMS/DMS.PL/Controllers/PatientController.cs
using DMS.BLL.Interfaces;
using DMS.BLL.Services;
using DMS.BLL.ViewModels;
using DMS.DAL.Entities;
using Microsoft.AspNetCore.Mvc;

namespace DMS.PL.Controllers
{
    public class PatientController : Controller
    {
        private readonly IPatientService patientService;

        public PatientController(IPatientService patientService) 
        {
            this.patientService = patientService;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(PatientVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await patientService.Create(model);
                    return RedirectToAction(nameof(Index));
                }
                return View(model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred while creating the Patient.");

            }
            return View(model);

        }
        [HttpGet]
        public async Task<IActionResult> GetPatientNames(string term)
        {
            var patients = await patientService.GetAll();
            var filteredPatients = patients
                .Where(p => p.Name.Contains(term, StringComparison.OrdinalIgnoreCase))
                .Select(p => new { p.Id, p.Name })
                .ToList();

            return Json(filteredPatients);
        }
        [HttpGet]
        public async Task<IActionResult> GetPatientIdByName(string name)
        {
            try
            {
                if (string.IsNullOrEmpty(name))
                {
                    return Json(new { patientId = (int?)null });
                }
                var patientId = await patientService.GetPatientIdByNameAsync(name);
                return Json(new { patientId });

            }
            catch (Exception ex)
            {
                await Console.Out.WriteLineAsync(ex.Message);
                return StatusCode(500, new { error = "An error occurred while retrieving the patient ID." });

            }
        }

    }
}

CMS/DMS.PL/Views/Appointment/Create.cshtml
@model AppointmentVM

@{
    ViewData["Title"] = "Create";
}

<h4 class="text-center"> Create Appointment </h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" >
            <div class="form-group">
                <label asp-for="PatientName" class="control-label">Patient Name</label>
                <input asp-for="PatientName" class="form-control" id="patientName" />
                <input asp-for="PatientId" type="hidden" id="patientId" />
                <span asp-validation-for="PatientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PatientBirthDate" class="control-label">Patient BirthDay</label>
                <input asp-for="PatientBirthDate" class="form-control" type="date" />
                <span asp-validation-for="PatientBirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PatientAddress" class="control-label">Patient Address</label>
                <input asp-for="PatientAddress" class="form-control" />
                <span asp-validation-for="PatientAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PatientPhoneNumber" class="control-label">Patient Phone Number</label>
                <input asp-for="PatientPhoneNumber" class="form-control" />
                <span asp-validation-for="PatientPhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PatientSSN" class="control-label">Patient SSN</label>
                <input asp-for="PatientSSN" class="form-control" />
                <span asp-validation-for="PatientSSN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoctorId" class="control-label">Doctor Name</label>
                <select asp-for="DoctorId" class="form-control" asp-items="ViewBag.Doctors">
                    <option value="">Select Doctor Name</option>
                </select>
                <span asp-validation-for="DoctorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppointmentDate" class="control-label">Appointment Date</label>
                <input asp-for="AppointmentDate" class="form-control" type="date"/>
                <span asp-validation-for="AppointmentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" type="time" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndTime" class="control-label"></label>
                <input asp-for="EndTime" class="form-control" type="time"/>
                <span asp-validation-for="EndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script type="text/javascript">
        $(document).ready(function () {
            $('#DoctorID, #AppointmentDate').change(function () {
                var doctorId = $('#DoctorID').val();
                var date = $('#AppointmentDate').val();

                if (doctorId && date) {
                    $.getJSON('@Url.Action("GetAvailableSlots", "Appointment")', { doctorId: doctorId, date: date }, function (data) {
                        var items = '<option value="">Select a time</option>';
                        $.each(data, function (i, slot) {
                            items += "<option value='" + slot.value + "'>" + slot.text + "</option>";
                        });
                        $('#StartTime').html(items);
                    });
                }
            });
            $('#StartTime').change(function () {
                var startTime = $(this).val();
                if (startTime) {
                    var endTime = new Date("1970-01-01T" + startTime + "Z");
                    endTime.setMinutes(endTime.getMinutes() + 30);
                    var formattedEndTime = endTime.toISOString().substring(11, 16);
                    $('#EndTime').val(formattedEndTime);
                } else {
                    $('#EndTime').val('');
                }
            });

            $('#patientName').on('change', function () {
                var selectedPatientName = $(this).val();

                $.getJSON('@Url.Action("GetPatientIdByName", "Patient")', { name: selectedPatientName })
            .done(function (data) {
                $('#patientId').val(data.patientId);
            })
            .fail(function (jqXHR, textStatus, errorThrown) {
                alert('Error: ' + errorThrown);
            });
            });
        });
    </script>
}

CMS/DMS.PL/Views/Appointment/Delete.cshtml
@model AppointmentVM

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Are you sure you want to delete this Appointment ?</h3>
<div>
    <hr />
    <dl class="row" >
        <dt class = "col-sm-2" hidden >
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10" hidden > 
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2"  hidden>
            @Html.DisplayNameFor(model => model.PatientId)
        </dt>
        <dd class = "col-sm-10" hidden>
            @Html.DisplayFor(model => model.PatientId)
        </dd>
        <dt class = "col-sm-2" hidden>
            @Html.DisplayNameFor(model => model.PatientName)
        </dt>
        <dd class = "col-sm-10" hidden>
            @Html.DisplayFor(model => model.PatientName)
        </dd>
        <dt class = "col-sm-2" hidden>
            @Html.DisplayNameFor(model => model.DoctorName)
        </dt>
        <dd class = "col-sm-10" hidden>
            @Html.DisplayFor(model => model.DoctorName)
        </dd>
        <dt class = "col-sm-2" hidden>
            @Html.DisplayNameFor(model => model.DoctorId)
        </dt>
        <dd class = "col-sm-10" hidden>
            @Html.DisplayFor(model => model.DoctorId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AppointmentDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppointmentDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartTime.ToString("hh:mm"))
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartTime.ToString("hh:mm"))
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndTime.ToString("hh:mm"))
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndTime.ToString("hh:mm"))
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CMS/DMS.PL/Views/Appointment/Edit.cshtml
@model AppointmentVM

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit Appointment</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div class="form-group" hidden>
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PatientName" class="control-label">Patient Name</label>
                <input asp-for="PatientName" class="form-control" id="patientName" />
                <input asp-for="PatientId" type="hidden" id="patientId" />
                <span asp-validation-for="PatientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PatientBirthDate" class="control-label">Patient BirthDay</label>
                <input asp-for="PatientBirthDate" class="form-control" type="date" />
                <span asp-validation-for="PatientBirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PatientAddress" class="control-label">Patient Address</label>
                <input asp-for="PatientAddress" class="form-control" />
                <span asp-validation-for="PatientAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PatientPhoneNumber" class="control-label"></label>
                <input asp-for="PatientPhoneNumber" class="form-control" />
                <span asp-validation-for="PatientPhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppointmentDate" class="control-label"></label>
                <input asp-for="AppointmentDate" class="form-control" />
                <span asp-validation-for="AppointmentDate" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="DoctorId" class="control-label">Doctor Name</label>
                <select asp-for="DoctorId" class="form-control" asp-items="ViewBag.Doctors">
                    <option value="">Select Doctor Name</option>
                </select>
                <span asp-validation-for="DoctorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndTime" class="control-label"></label>
                <input asp-for="EndTime" class="form-control" />
                <span asp-validation-for="EndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn- btn-outline-success">Back to List</a>
</div>

CMS/DMS.PL/Views/Appointment/Index.cshtml
@model IEnumerable<AppointmentVM>

@{
    ViewData["Title"] = "Index";
    Layout = "/Views/Shared/_Layout.cshtml";
}
<h1 class="custom-heading">All Appointments</h1>

<p>
    <a asp-action="Create" class="btn btn-primary mb-4">Create New Appointment </a>
</p>
<div class="table-responsive">
    <table class="table table-striped table-hover table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Patient</th>
                <th>Patient BirthDate</th>
                <th>Patient Address</th>
                <th>Phone Number</th>
                <th>Appointment Date</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Status</th>
                <th>Doctor</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var appointment in Model)
            {
                <tr>
                    <td>@appointment.PatientName</td>
                    <td>@appointment.PatientBirthDate.ToString("yyyy-MM-dd")</td>
                    <td>@appointment.PatientAddress</td>
                    <td>@appointment.PatientPhoneNumber</td>
                    <td>@appointment.AppointmentDate.ToString("yyyy-MM-dd")</td>
                    <td>@appointment.StartTime.ToString("HH:mm")</td>
                    <td>@appointment.EndTime.ToString("HH:mm")</td>
                    <td>@appointment.Status</td>
                    <td>@appointment.DoctorName</td>

                    <td>
                        <a asp-action="Edit" asp-route-id="@appointment.Id" class="btn btn-outline-success btn-sm">Edit</a>
                    </td>
                   
                    <td>
                        <a asp-action="Delete" asp-route-id="@appointment.Id" class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>